[package]
name = "pxsort"
description = "Sort the pixels in an image"
version = "0.1.0"
authors = ["George Kaplan <george@georgekaplan.xyz>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/g-s-k/pxsort"

[dependencies]
image = "0.21.0"
structopt = "0.2.15"
