name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build_web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-web
        version: latest
        use-tool-cache: true
    - name: Build
      run: cargo web deploy --package www --release
    - name: Deploy
      if: github.ref == 'master'
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: gh-pages
        github_token: ${{ github.token }}
